### ISSUE TITLE
Feature request: allow configuring the domain for self-hosted Healthchecks instances

### ISSUE THREAD

**Issue by phirk** [arturoiafrate/homey.heathchecks-io#1]
Nice work!

This works great for the hosted service [healthchecks.io](https://healthchecks.io), but not for [self-hosted](https://healthchecks.io/docs/self_hosted/) instances, since users can only configure the UUID, but not the domain.

Please support self-hosted instances, by allowing (advanced) users to configure the domain as well, or even the entire URL.

The latter is beneficial for other purposes as well. For example, I prefer to using "ping key" + "slug" above UUID.

**Comment by arturoiafrate** [comment]
Hi and thanks. Custom url will be available in the next release 👍

**Comment by arturoiafrate** [comment]
Hi, the version 1.2.0 with custom url support is in testing: https://homey.app/a/it.arturoiafrate.heathchecks-io/test/
If everything works fine, i'll release it.
